# Generated by Django 5.2.17 on 2026-09-27 08:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adjustment_number", models.CharField(max_length=20, unique=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Positive increases stock, negative decreases it.",
                        max_digits=14,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged goods"),
                            ("EXPIRED", "Expired"),
                            ("LOST", "Lost / theft"),
                            ("COUNT_CORRECTION", "Physical count correction"),
                            ("FOUND", "Found / surplus"),
                            ("RETURN", "Returned goods"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("stock_before", models.DecimalField(decimal_places=3, max_digits=14)),
                ("stock_after", models.DecimalField(decimal_places=3, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_adjustments",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity", 0), _negated=True),
                        name="adjustment_quantity_not_zero",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("OPENING_STOCK", "Opening stock"),
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("PURCHASE_CANCEL", "Purchase cancellation"),
                            ("SALE_CANCEL", "Sale cancellation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("reference_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                (
                    "quantity_in",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "quantity_out",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "running_balance",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(
                        fields=["product", "date", "id"],
                        name="stockmove_product_date_idx",
                    ),
                    models.Index(
                        fields=["product", "-id"], name="stockmove_product_latest_idx"
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="stockmove_reference_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_in__gte", 0)),
                        name="stockmove_qty_in_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity_out__gte", 0)),
                        name="stockmove_qty_out_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("quantity_in__gt", 0), ("quantity_out", 0)),
                            models.Q(("quantity_in", 0), ("quantity_out__gt", 0)),
                            _connector="OR",
                        ),
                        name="stockmove_exactly_one_direction",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("running_balance__gte", 0)),
                        name="stockmove_no_negative_stock",
                    ),
                ],
            },
        ),
    ]
