# Generated by Django 5.2.17 on 2026-09-27 08:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("due_date", models.DateField(db_index=True)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Sum of gross line amounts.",
                        max_digits=16,
                    ),
                ),
                (
                    "item_discount_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed amount"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Invoice-level discount amount.",
                        max_digits=16,
                    ),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Derived from payment allocations; never edited directly.",
                        max_digits=16,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("UNPAID", "Unpaid"),
                        ],
                        db_index=True,
                        default="UNPAID",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CANCELLED", "Cancelled")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "bill_number",
                    models.CharField(
                        help_text="Internal number, e.g. BILL-000001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "vendor_bill_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Supplier's own invoice number.",
                        max_length=60,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="parties.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed amount"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Item-level discount amount.",
                        max_digits=16,
                    ),
                ),
                (
                    "invoice_discount_share",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=7)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=16)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="products.product",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchase",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["vendor", "date"], name="purchases_p_vendor__839870_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["status", "payment_status", "due_date"],
                name="purchases_p_status_fb3d5e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)), name="purchase_subtotal_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_discount_total__gte", 0)),
                name="purchase_item_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0)),
                name="purchase_discount_value_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="purchase_discount_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("taxable_amount__gte", 0)),
                name="purchase_taxable_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="purchase_tax_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="purchase_total_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_paid__gte", 0),
                    ("amount_paid__lte", models.F("total_amount")),
                ),
                name="purchase_amount_paid_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_date__gte", models.F("date"))),
                name="purchase_due_after_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="purchaseitem_quantity_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="purchaseitem_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("gross_amount__gte", 0)),
                name="purchaseitem_gross_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0)),
                name="purchaseitem_discount_value_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="purchaseitem_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("invoice_discount_share__gte", 0)),
                name="purchaseitem_inv_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("taxable_amount__gte", 0)),
                name="purchaseitem_taxable_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 100)),
                name="purchaseitem_tax_rate_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)),
                name="purchaseitem_tax_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_cost__gte", 0)),
                name="purchaseitem_total_gte_0",
            ),
        ),
    ]
