# Generated by Django 5.2.17 on 2026-09-27 08:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_name",
                    models.CharField(default="My Business Pvt. Ltd.", max_length=200),
                ),
                ("address", models.TextField(blank=True, default="Kathmandu, Nepal")),
                (
                    "pan_vat_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="PAN/VAT No.",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("currency_code", models.CharField(default="NPR", max_length=3)),
                ("currency_symbol", models.CharField(default="Rs.", max_length=8)),
                ("tax_label", models.CharField(default="VAT", max_length=20)),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("13.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "invoice_footer",
                    models.CharField(
                        blank=True,
                        default="Thank you for your business.",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business settings",
                "verbose_name_plural": "Business settings",
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("prefix", models.CharField(max_length=16)),
                ("padding", models.PositiveSmallIntegerField(default=6)),
                ("last_number", models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
