# Generated by Django 5.2.17 on 2026-09-27 08:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("VENDOR", "Vendor")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "pan_vat_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=30,
                        verbose_name="PAN/VAT No.",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "credit_terms",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("DAYS_7", "7 Days"),
                            ("DAYS_15", "15 Days"),
                            ("DAYS_30", "30 Days"),
                            ("DAYS_45", "45 Days"),
                            ("DAYS_60", "60 Days"),
                            ("DAYS_90", "90 Days"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("credit_days", models.PositiveIntegerField(default=0)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name_plural": "parties",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["type", "name"], name="parties_par_type_ea7514_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("credit_limit__gte", 0)),
                        name="party_credit_limit_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("credit_days__lte", 3650)),
                        name="party_credit_days_lte_3650",
                    ),
                ],
            },
        ),
    ]
