# Generated by Django 5.2.17 on 2026-10-05 12:04

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='expensecategory_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('payee', models.CharField(blank=True, default='', help_text='Paid to, when not a registered vendor.', max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount excluding tax.', max_digits=16)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Transfer'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Bill no., cheque no., bank ref, etc.', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Optional: the vendor that was paid.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='parties.party')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['category', 'date'], name='expenses_ex_categor_9e3535_idx'), models.Index(fields=['vendor', 'date'], name='expenses_ex_vendor__865e90_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_gt_0'), models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='expense_tax_rate_0_100'), models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='expense_tax_gte_0'), models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('amount'), '+', models.F('tax_amount')))), name='expense_total_is_amount_plus_tax')],
            },
        ),
    ]
