# Generated by Django 5.2.17 on 2026-09-27 08:44

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("CANCEL", "Cancel"),
                            ("ACTIVATE", "Activate"),
                            ("DEACTIVATE", "Deactivate"),
                            ("ALLOCATE", "Allocate"),
                            ("LOGIN", "Login"),
                            ("LOGIN_FAILED", "Login failed"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password change"),
                            ("PASSWORD_RESET", "Password reset"),
                            ("PERMISSION_CHANGE", "Permission change"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                (
                    "object_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "before_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "after_data",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_audit_model_n_20c0d3_idx",
                    )
                ],
            },
        ),
    ]
