# Generated by Django 5.2.17 on 2026-09-27 08:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
        ("purchases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank"),
                            ("CHEQUE", "Cheque"),
                            ("ONLINE", "Online Transfer"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cheque no., bank ref, etc.",
                        max_length=60,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CANCELLED", "Cancelled")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("payment_number", models.CharField(max_length=20, unique=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_payments",
                        to="parties.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("date", models.DateField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="payables.vendorpayment",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="purchases.purchase",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="vendorpayment",
            index=models.Index(
                fields=["vendor", "date"], name="payables_ve_vendor__3ce4d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="vendorpayment_amount_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_amount__gte", 0),
                    ("allocated_amount__lte", models.F("amount")),
                ),
                name="vendorpayment_allocated_within_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpaymentallocation",
            index=models.Index(
                fields=["purchase", "is_active"], name="payables_ve_purchas_633d6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorpaymentallocation",
            index=models.Index(
                fields=["payment", "is_active"], name="payables_ve_payment_2ab4a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorpaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="vendorpaymentalloc_amount_gt_0",
            ),
        ),
    ]
