# Generated by Django 5.2.17 on 2026-09-27 08:46

import apps.products.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "sku_code",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="SKU"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PCS", "Pcs"),
                            ("KG", "Kg"),
                            ("BOX", "Box"),
                            ("LTR", "Ltr"),
                            ("METER", "Meter"),
                            ("SET", "Set"),
                            ("PACK", "Pack"),
                            ("DOZEN", "Dozen"),
                        ],
                        default="PCS",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "opening_stock",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=apps.products.models.default_tax_rate,
                        max_digits=7,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("opening_stock__gte", 0)),
                        name="product_opening_stock_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reorder_level__gte", 0)),
                        name="product_reorder_level_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("purchase_price__gte", 0)),
                        name="product_purchase_price_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("selling_price__gte", 0)),
                        name="product_selling_price_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tax_rate__gte", 0), ("tax_rate__lte", 100)
                        ),
                        name="product_tax_rate_0_100",
                    ),
                ],
            },
        ),
    ]
